"""
Transparency label generator.

Maps a confidence score to the exact user-facing label text defined in planning.md.

Thresholds (same as pipeline._classify):
  < 0.45  → Likely Human-Written
  0.45–0.69 → Unable to Determine
  ≥ 0.70  → Likely AI-Generated
"""

# Exact wording from planning.md — do not paraphrase.
_LABELS = {
    "human": {
        "title": "Likely Human-Written",
        "body": (
            "Our analysis indicates with high confidence that this content was written by a person. "
            "This result is based on multiple detection signals and is not proof of authorship."
        ),
    },
    "uncertain": {
        "title": "Unable to Determine",
        "body": (
            "Our analysis found mixed evidence. We cannot confidently determine whether this content "
            "was written by a person or generated by AI."
        ),
    },
    "ai": {
        "title": "Likely AI-Generated",
        "body": (
            "Our analysis indicates with high confidence that this content was generated using AI. "
            "This result is based on multiple detection signals and is not proof of authorship."
        ),
    },
}


def generate_label(confidence_score: float) -> dict:
    """
    Return the transparency label for the given confidence score.

    Returns:
        {"title": str, "body": str}
    """
    if confidence_score < 0.45:
        return _LABELS["human"]
    if confidence_score < 0.70:
        return _LABELS["uncertain"]
    return _LABELS["ai"]
