"""
Signal 1 – Groq LLM Classifier (Llama 3.3 70B Versatile)

Returns a normalized score in [0.0, 1.0]:
  0.0 → strongly human-written
  0.5 → uncertain
  1.0 → strongly AI-generated
"""

import json
import os
from typing import Optional

from groq import Groq

_client: Optional[Groq] = None

_SYSTEM_PROMPT = """\
You are a writing analysis assistant. Analyze the submitted text and estimate \
the probability that it was generated by an AI language model rather than written by a human.

Return ONLY a valid JSON object with exactly two fields:
- "score": a float between 0.0 and 1.0
    0.0 = the text is strongly human-written
    0.5 = genuinely uncertain
    1.0 = the text is strongly AI-generated
- "reason": a concise 1-2 sentence explanation citing the main stylistic evidence

Output only the JSON object. No preamble, no extra text.\
"""


def _get_client() -> Groq:
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise EnvironmentError("GROQ_API_KEY environment variable is not set.")
        _client = Groq(api_key=api_key)
    return _client


def analyze_with_groq(text: str) -> dict:
    """
    Classify text using the Groq LLM.

    Args:
        text: The text to analyze.

    Returns:
        {"score": float, "reason": str}
        On a malformed model response: adds "parse_error": True and defaults score to 0.5.
    """
    client = _get_client()

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": f"Analyze this text:\n\n{text}"},
        ],
        response_format={"type": "json_object"},
        temperature=0.1,
        max_tokens=256,
    )

    raw = response.choices[0].message.content

    try:
        result = json.loads(raw)
        score = max(0.0, min(1.0, float(result["score"])))
        reason = str(result.get("reason", ""))
        return {"score": score, "reason": reason}
    except (json.JSONDecodeError, KeyError, ValueError) as exc:
        # Return uncertain rather than crashing; caller can check parse_error.
        return {"score": 0.5, "reason": "Model response could not be parsed.", "parse_error": True}
